### ISSUE TITLE
run-flownet-many.py gives CUDNN error after some time

### ISSUE THREAD

**Issue by gulvarol** [lmb-freiburg/flownet2#22]
I am trying to extract flow from many image pairs by using `run-flownet-many.py`

I have a list.txt file with ~300K lines. The execution stops after running 290 image pairs successfully on GTX1080 (with 8GB GPU memory) with an error message:

`WARNING: Logging before InitGoogleLogging() is written to STDERR
F0601 17:53:43.127583 35329 cudnn_conv_layer.cpp:52] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Aborted (core dumped)`

and stops after running 490 image pairs successfully on Titan X (with 12GB GPU memory) with an error message:

`WARNING: Logging before InitGoogleLogging() is written to STDERR
F0601 18:01:21.865638 76360 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
*** Check failure stack trace: ***
Aborted (core dumped)`

I have tried this only a few times, but thought maybe you have a guess why this could be happening. I am using CUDNNv6 and compiled after doing changes suggested in #17 .

Thanks!

**Comment by nikolausmayer** [comment]
Hi Gül,

do all of the input images have the same dimensions? Is the image pair #290 perhaps very large?

It's also possible that we have a small memory leak somewhere which only becomes relevant after running for a long time (I don't think we ever tried processing *300.000* image pairs). Maybe it works if you chop up your `list.txt` into 100 smaller lists?

Best,
 Nikolaus

**Comment by gulvarol** [comment]
The images are all of same resolution (240x320). Ok I will divide the jobs into smaller lists, then. Thanks a lot.

**Comment by playerkk** [comment]
I think the memory leak is related to the repeated initialization of a network. By removing the line #77 to #81 into the if clause, the memory leak can be greatly alleviated. If all of the input images have the same dimension, the memory consumption is pretty steady.

**Comment by nikolausmayer** [comment]
Ah yes, that sounds good. We never used the network on multiple resolutions in one run, so we never thought of this a possible problem :)
